"""
CS 1430 Assignment 2: The Cost of College
Self-check and receipt writer.  DO NOT EDIT THIS FILE.

Run it from this folder:
    python check.py

Every run writes SUBMISSION.txt with your points so far (out of 40).
Upload that file to Canvas when you are done.

Uses only the Python standard library. Nothing to install.
"""

import ast
import datetime
import json
import os
import re
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
MAIN = os.path.join(HERE, "main.py")
NOTES = os.path.join(HERE, "AI_NOTES.md")
RECEIPT = os.path.join(HERE, "SUBMISSION.txt")
RUN_SECONDS = 10

# ---------------------------------------------------------------------------
# What the template promises
# ---------------------------------------------------------------------------
CONSTANTS = {
    "SEMESTERS_PER_YEAR": 2,
    "MONTHS_PER_YEAR": 9,
    "CLASS_DAYS_PER_SEMESTER": 75,
    "CS1430_CREDITS": 3,
    "CS1430_MEETINGS_PER_SEMESTER": 45,
}

FUNCTIONS = [
    # (name, number of parameters)
    ("cost_per_semester", 1),
    ("cost_per_month", 1),
    ("cost_per_day", 1),
    ("cost_per_credit", 2),
    ("cost_per_class", 2),
]

# (annual cost, credits this semester). The first pair is the guide's example.
TEST_PAIRS = [(14601, 15), (24000, 12), (9876.54, 17)]

TOLERANCE = 0.005  # half a cent


def expected(name, cost, credits):
    """The right answers, unrounded."""
    if name == "cost_per_semester":
        return cost / 2
    if name == "cost_per_month":
        return cost / 9
    if name == "cost_per_day":
        return cost / (2 * 75)
    if name == "cost_per_credit":
        return cost / (2 * credits)
    if name == "cost_per_class":
        return cost / (2 * credits) * 3 / 45
    raise ValueError(name)


def common_mistake(name, cost, credits, got):
    """If a wrong answer matches a known mistake, explain it."""
    guesses = {
        "cost_per_semester": [
            (cost, "That is the whole year. A year has SEMESTERS_PER_YEAR semesters."),
        ],
        "cost_per_month": [
            (cost / 12, "That uses a 12-month year. The academic year is MONTHS_PER_YEAR months."),
            (cost / 2 / 9, "That spreads one semester over 9 months. Use the whole year's cost."),
        ],
        "cost_per_day": [
            (cost / 365, "That uses 365 calendar days. A day here means a class day."),
            (cost / 75, "That is a full year over one semester's class days. A year has two semesters."),
            (cost / 2 / 5, "That uses 5 days. CLASS_DAYS_PER_SEMESTER is the number of class days."),
        ],
        "cost_per_credit": [
            (cost / credits, "That is the whole year over one semester's credits. Use one semester's cost."),
        ],
        "cost_per_class": [
            (cost / (2 * credits) / 45, "That is one credit over 45 meetings. CS 1430 is CS1430_CREDITS credits."),
            (cost / 2 / 45, "That is the whole semester over 45 meetings. Use only CS 1430's share of the semester."),
            (cost / (2 * credits) * 3, "That is what all of CS 1430 costs for the semester. Divide by the meetings."),
        ],
    }
    for value, hint in guesses.get(name, []):
        if abs(got - value) <= TOLERANCE:
            return hint
    return None


def money(x):
    return "{:.2f}".format(x)


def show_pair(cost, credits, name):
    c = ("{:.2f}".format(cost)).rstrip("0").rstrip(".")
    if dict(FUNCTIONS)[name] == 1:
        return "annual_cost = {}".format(c)
    return "annual_cost = {}, credits = {}".format(c, credits)


# ---------------------------------------------------------------------------
# Results table
# ---------------------------------------------------------------------------
RESULTS = []   # (status, label, [hint lines], blocking, (earned, possible) or None)
POINTS_POSSIBLE = 40
NOTES_OUT = []


def record(ok, label, hints=None, blocking=True, pts=None):
    RESULTS.append(("PASS" if ok else "FAIL", label, hints or [], blocking,
                    (pts if ok else 0, pts) if pts else None))
    return ok


def record_partial(label, earned, possible, hints=None):
    ok = earned == possible
    RESULTS.append(("PASS" if ok else "FAIL", label, hints or [], True, (earned, possible)))
    return ok


def skip(label, why, pts=None):
    RESULTS.append(("SKIP", label, [why], True, (0, pts) if pts else None))


def heading(text):
    RESULTS.append(("HEAD", text, [], False, None))


def points_earned():
    return sum(r[4][0] for r in RESULTS if r[4])


# ---------------------------------------------------------------------------
# Running student code safely, in a separate Python process
# ---------------------------------------------------------------------------
def child_env():
    env = dict(os.environ)
    env["PYTHONIOENCODING"] = "utf-8"
    env["PYTHONDONTWRITEBYTECODE"] = "1"
    return env


def run_program(lines):
    """Run main.py with these lines typed in. Returns (status, stdout, stderr)."""
    typed = "\n".join(lines) + "\n"
    try:
        p = subprocess.run(
            [sys.executable, MAIN], input=typed, capture_output=True, text=True,
            encoding="utf-8", errors="replace", cwd=HERE, env=child_env(), timeout=RUN_SECONDS,
        )
    except subprocess.TimeoutExpired as e:
        out = e.stdout.decode("utf-8", "replace") if isinstance(e.stdout, bytes) else (e.stdout or "")
        return "timeout", out, ""
    return ("ok" if p.returncode == 0 else "error"), p.stdout, p.stderr


FUNCTION_PROBE = r'''
import importlib, json, sys, traceback
sys.path.insert(0, sys.argv[1])
cases = json.loads(sys.argv[2])
report = {"import": "ok", "detail": "", "functions": {}}
try:
    m = importlib.import_module("main")
except EOFError:
    report["import"] = "asked_for_input"
except BaseException as e:
    report["import"] = "error"
    report["detail"] = traceback.format_exception_only(type(e), e)[-1].strip()
else:
    for name, args_list in cases.items():
        f = getattr(m, name, None)
        entry = {"exists": callable(f), "results": []}
        if callable(f):
            for args in args_list:
                try:
                    v = f(*args)
                    if isinstance(v, bool):
                        entry["results"].append({"kind": "other", "repr": repr(v)})
                    elif isinstance(v, (int, float)):
                        entry["results"].append({"kind": "number", "value": float(v)})
                    elif v is None:
                        entry["results"].append({"kind": "none"})
                    elif isinstance(v, str):
                        entry["results"].append({"kind": "text", "repr": repr(v)})
                    else:
                        entry["results"].append({"kind": "other", "repr": repr(v)})
                except BaseException as e:
                    entry["results"].append({"kind": "crash",
                        "repr": traceback.format_exception_only(type(e), e)[-1].strip()})
        report["functions"][name] = entry
print()
print("@@REPORT@@" + json.dumps(report))
'''


def probe_functions():
    cases = {}
    for name, nparams in FUNCTIONS:
        cases[name] = [[cost, credits][:nparams] for cost, credits in TEST_PAIRS]
    try:
        p = subprocess.run(
            [sys.executable, "-c", FUNCTION_PROBE, HERE, json.dumps(cases)],
            stdin=subprocess.DEVNULL, capture_output=True, text=True, encoding="utf-8",
            errors="replace", cwd=HERE, env=child_env(), timeout=RUN_SECONDS,
        )
    except subprocess.TimeoutExpired:
        return {"import": "timeout", "detail": "", "functions": {}}
    for line in p.stdout.splitlines():
        if "@@REPORT@@" in line:
            return json.loads(line.split("@@REPORT@@", 1)[1])
    last = (p.stderr.strip().splitlines() or ["unknown problem"])[-1]
    return {"import": "error", "detail": last, "functions": {}}


AMOUNT = re.compile(r"(?<![\d.])\d[\d,]*\.\d{2}(?![\d])")


def amounts_in(text):
    return {a.replace(",", "") for a in AMOUNT.findall(text)}


def last_error_line(stderr):
    lines = [l for l in stderr.strip().splitlines() if l.strip()]
    return lines[-1].strip() if lines else "unknown error"


def explain_crash(stderr):
    err = last_error_line(stderr)
    hints = ["Python said: " + err]
    if err.startswith("EOFError"):
        hints.append("Your program asked for more input than expected. Ask for cost and credits")
        hints.append("once, before the menu, and make Q end the loop.")
    elif "ValueError" in err and "int()" in err:
        hints.append("The yearly cost can have cents (like 9876.54). Convert it with float(), not int().")
    elif "unsupported operand" in err and "'str'" in err:
        hints.append("input() always gives back text. Convert it with float() or int() before doing math.")
    elif "NoneType" in err:
        hints.append("One of your functions gave back None. Make each function return its answer.")
    elif "of type 'str'" in err:
        hints.append("One of your functions gave back text. Return the number; format it only when printing.")
    elif err.startswith("NameError"):
        hints.append("Check the spelling and capitals of every name. Copy names from the template.")
    elif err.startswith(("SyntaxError", "IndentationError")):
        hints.append("Look at the line number in the message, and the line just above it.")
    return hints


# ---------------------------------------------------------------------------
# Git helpers
# ---------------------------------------------------------------------------
def git(*args, timeout=20):
    try:
        p = subprocess.run(["git"] + list(args), capture_output=True, text=True, encoding="utf-8",
                           errors="replace", cwd=HERE, timeout=timeout)
        return p.returncode, p.stdout.strip(), p.stderr.strip()
    except (OSError, subprocess.TimeoutExpired) as e:
        return 1, "", str(e)


# ===========================================================================
# THE CHECKS
# ===========================================================================
def main():
    print()
    print("CS 1430 Assignment 2: The Cost of College")
    print("Checking your work. This takes a few seconds...")

    # ---------------- Toolchain ----------------
    heading("Toolchain")
    v = sys.version_info
    record(v >= (3, 8), "Python {}.{}.{} is installed".format(v.major, v.minor, v.micro),
           ["Python 3.8 or newer is required. Install it from https://www.python.org/downloads/"])

    has_main = record(os.path.isfile(MAIN), "main.py is in this folder",
                      ["Open the whole Assignment2 folder in VS Code (File > Open Folder),",
                       "not a single file, and run check.py from there."])

    tree = None
    source = ""
    if has_main:
        with open(MAIN, encoding="utf-8", errors="replace") as fh:
            source = fh.read()
        try:
            tree = ast.parse(source)
        except SyntaxError as e:
            record(False, "main.py runs without an error",
                   ["Python found a syntax error on line {}: {}".format(e.lineno, e.msg),
                    "Look at that line and the line just above it."])

    probe = None
    if tree is not None:
        probe = probe_functions()
        if probe["import"] == "ok":
            record(True, "main.py runs without an error")
        elif probe["import"] == "asked_for_input":
            record(False, "main.py runs without an error",
                   ["Your program started asking for input as soon as the file was loaded.",
                    "Keep your input() calls inside main(), and keep the launch lines at the bottom."])
        elif probe["import"] == "timeout":
            record(False, "main.py runs without an error",
                   ["Loading main.py never finished. Look for a loop outside of main()."])
        else:
            record(False, "main.py runs without an error", explain_crash(probe["detail"]))

    if tree is not None:
        found = {}
        for node in tree.body:
            if isinstance(node, ast.Assign) and len(node.targets) == 1 and isinstance(node.targets[0], ast.Name):
                if isinstance(node.value, ast.Constant):
                    found[node.targets[0].id] = node.value.value
        wrong = [n for n, val in CONSTANTS.items() if found.get(n) != val]
        record(not wrong, "The constants are unchanged",
               ["Changed or missing: " + ", ".join(wrong),
                "Copy the CONSTANTS section back from the template on GitHub."] if wrong else None)

        launch_ok = False
        for node in tree.body:
            if isinstance(node, ast.If) and isinstance(node.test, ast.Compare):
                t = node.test
                if (isinstance(t.left, ast.Name) and t.left.id == "__name__" and len(t.comparators) == 1
                        and isinstance(t.comparators[0], ast.Constant) and t.comparators[0].value == "__main__"):
                    for s in node.body:
                        if (isinstance(s, ast.Expr) and isinstance(s.value, ast.Call)
                                and isinstance(s.value.func, ast.Name) and s.value.func.id == "main"):
                            launch_ok = True
        record(launch_ok, "The launch lines are in place",
               ["The last two lines of main.py must be:",
                '    if __name__ == "__main__":',
                "        main()",
                "Copy them back from the template on GitHub."])
    elif has_main:
        skip("The constants are unchanged", "Fix the error in main.py first.")
        skip("The launch lines are in place", "Fix the error in main.py first.")

    # ---------------- Functions ----------------
    heading("Your five functions (6 points each)")
    for name, nparams in FUNCTIONS:
        label = "{} gives back the right values".format(name)
        if probe is None or probe["import"] != "ok":
            skip(label, "Fix the first FAIL above, then run check.py again.", pts=6)
            continue
        entry = probe["functions"].get(name, {})
        if not entry.get("exists"):
            record(False, label, ["main.py has no function named {}.".format(name),
                                  "Spelling and underscores must match exactly."], pts=6)
            continue
        hints = []
        for (cost, credits), res in zip(TEST_PAIRS, entry["results"]):
            want = expected(name, cost, credits)
            where = show_pair(cost, credits, name)
            kind = res["kind"]
            if kind == "number" and abs(res["value"] - want) <= TOLERANCE:
                continue
            if kind == "number":
                got = res["value"]
                shown = "0" if got == 0 else "{:.4f}".format(got).rstrip("0").rstrip(".")
                hints.append("For {}, expected {} but got {}".format(where, money(want), shown))
                if got == 0:
                    hints.append("Still returning 0? Replace the stub with your calculation.")
                else:
                    hints.append(common_mistake(name, cost, credits, got)
                                 or "Re-read what this result means in section 7 of the guide, and use the constants.")
            elif kind == "none":
                hints.append("For {}, expected {} but got None".format(where, money(want)))
                hints.append("The function needs to return its answer. Print in main(), not here.")
            elif kind == "text":
                hints.append("For {}, expected the number {} but got text: {}".format(where, money(want), res["repr"]))
                hints.append("Return the number itself. Format it as money only when you print it.")
            elif kind == "crash":
                hints.append("For {}, the function crashed: {}".format(where, res["repr"]))
            else:
                hints.append("For {}, expected {} but got {}".format(where, money(want), res["repr"]))
            break  # one clear message is better than three
        record(not hints, label, hints, pts=6)

    # ---------------- The program ----------------
    heading("Your program (10 points)")
    transcript = ""
    run_label = "The menu runs from start to Q without an error"
    show_label = "Options 1 to 5 print all five amounts"
    if probe is None or probe["import"] != "ok":
        skip(run_label, "Fix the first FAIL above, then run check.py again.", pts=5)
        skip(show_label, "Fix the first FAIL above, then run check.py again.", pts=5)
    else:
        crash = None
        missing = []
        for i, (cost, credits) in enumerate(TEST_PAIRS):
            typed = [str(cost), str(credits), "1", "2", "3", "4", "5", "Q"]
            status, out, err = run_program(typed)
            if i == 0:
                transcript = out
            if status == "timeout":
                crash = ["With cost {} and {} credits, your program never finished.".format(cost, credits),
                         "Make sure Q breaks out of the loop, and that nothing loops forever."]
                break
            if status == "error":
                crash = ["With cost {} and {} credits typed in:".format(cost, credits)] + explain_crash(err)
                break
            seen = amounts_in(out)
            for name, _ in FUNCTIONS:
                want = money(expected(name, cost, credits))
                if want not in seen:
                    missing.append((cost, credits, name, want))
        if crash is None and len({m[2] for m in missing}) == len(FUNCTIONS) and len(missing) == len(FUNCTIONS) * len(TEST_PAIRS):
            crash = ["Your program ran to Q, but none of the five amounts ever appeared.",
                     "Add the two input prompts and connect menu options 1 to 5 to your functions."]
            record(False, run_label, crash, pts=5)
            skip(show_label, "Fix the FAIL above first.", pts=5)
            crash = "shown"
        else:
            record(crash is None, run_label, crash, pts=5)
        if crash == "shown":
            pass
        elif crash is not None:
            skip(show_label, "Fix the FAIL above first.", pts=5)
        else:
            hints = []
            if missing:
                cost, credits, _, _ = missing[0]
                these = [m for m in missing if m[0] == cost]
                hints.append("With cost {} and {} credits, these amounts were not found in output:".format(cost, credits))
                for _, _, name, want in these:
                    hints.append("    {}  (from {})".format(want, name))
                hints.append("Each amount must be printed with exactly two decimals, like 97.34.")
                hints.append("check.py types: cost, credits, 1, 2, 3, 4, 5, Q.")
            missing_names = {m[2] for m in missing}
            record_partial(show_label, 5 - len(missing_names), 5, hints)

    # ---------------- Git and GitHub ----------------
    heading("Git and GitHub (required for your points to count)")
    git_path = shutil.which("git")
    commit = {}
    repo_url = ""
    gh_user = ""
    ok = record(git_path is not None, "Git is installed",
                ["Install Git from https://git-scm.com/install/ , then close and reopen VS Code."])
    if ok:
        rc, top, _ = git("rev-parse", "--show-toplevel")
        ok = record(rc == 0, "This folder is a Git repository",
                    ["Clone your repo with git clone (see the guide), then open that folder."])
    if ok:
        rc, count, _ = git("rev-list", "--count", "HEAD")
        ok = record(rc == 0 and count.isdigit() and int(count) > 1, "You have committed your own work",
                    ["So far there is only the template's first commit.",
                     "In Source Control, type a message and click Commit."])
    if ok:
        rc, dirty, _ = git("status", "--porcelain", "--", "main.py", "AI_NOTES.md")
        ok = record(rc == 0 and dirty == "", "Your latest changes are committed",
                    ["main.py or AI_NOTES.md has changes that are not committed yet.",
                     "Save, then Commit in Source Control, so GitHub has what check.py tested."])
    if ok:
        rc, url, _ = git("remote", "get-url", "origin")
        ok = record(rc == 0 and "github.com" in url, "Your repo is connected to GitHub",
                    ["This folder has no GitHub remote. Clone your own repo from GitHub (see the guide)."])
        if ok:
            repo_url = re.sub(r"\.git$", "", url)
            repo_url = re.sub(r"^git@github\.com:", "https://github.com/", repo_url)
            m = re.search(r"github\.com[/:]([^/]+)/", url)
            gh_user = m.group(1) if m else ""
            if re.search(r"github\.com[/:]cs1430/", url, re.IGNORECASE):
                ok = record(False, "This is your own copy, not the class template",
                            ["origin points at the CS1430 template. Use the template button to make",
                             "your own repo, then clone that one."])
    if ok:
        rc, head, _ = git("rev-parse", "HEAD")
        rc2, remote, err2 = git("ls-remote", "origin", "HEAD", timeout=30)
        remote_sha = remote.split()[0] if remote else ""
        if rc2 != 0:
            ok = record(False, "Your commit is pushed to GitHub",
                        ["Could not reach GitHub: " + (err2.splitlines()[-1] if err2 else "no response"),
                         "Check your internet connection, then run check.py again."])
        else:
            ok = record(head == remote_sha, "Your commit is pushed to GitHub",
                        ["Committing saves your work on this computer. PUSH sends it to GitHub.",
                         "Click Sync Changes in Source Control (or run git push), then run this file again."])
        if ok:
            rc, line, _ = git("log", "-1", "--format=%H%n%s%n%an <%ae>%n%cI")
            parts = line.splitlines()
            if len(parts) >= 4:
                commit = {"sha": parts[0], "message": parts[1], "author": parts[2], "date": parts[3]}

    # ---------------- Non-blocking notes ----------------
    if os.path.isfile(NOTES):
        with open(NOTES, encoding="utf-8", errors="replace") as fh:
            if "(write here)" in fh.read():
                NOTES_OUT.append("AI_NOTES.md still has (write here) placeholders. Fill it in before you submit.")
    else:
        NOTES_OUT.append("AI_NOTES.md is missing. Copy it back from the template on GitHub.")

    # ---------------- Report ----------------
    report = render_report()
    print(report)

    complete = all(r[0] == "PASS" for r in RESULTS if r[3] and r[0] != "HEAD")
    write_receipt(report, complete, commit, repo_url, gh_user, transcript)
    if complete:
        print("ALL CHECKS PASSED: {} / {} points.".format(points_earned(), POINTS_POSSIBLE))
        print("SUBMISSION.txt has been written to this folder. Upload it to Canvas.")
    else:
        print("Not done yet. Fix the FIRST line that says FAIL, then run check.py again.")
        print("(SUBMISSION.txt was updated with your points so far.)")
    print()
    return 0 if complete else 1


def render_report():
    lines = []
    for status, label, hints, _, pts in RESULTS:
        if status == "HEAD":
            lines.append("")
            lines.append("--- {} ---".format(label))
            continue
        tag = "  ({}/{} pts)".format(*pts) if pts else ""
        lines.append("[{}] {}{}".format(status, label, tag))
        if status == "FAIL":
            for h in hints:
                lines.append("   > " + h)
    lines.append("")
    lines.append("POINTS FROM check.py: {} / {}".format(points_earned(), POINTS_POSSIBLE))
    if NOTES_OUT:
        lines.append("")
        for n in NOTES_OUT:
            lines.append("NOTE: " + n)
    lines.append("")
    return "\n".join(lines)


def write_receipt(report, complete, commit, repo_url, gh_user, transcript):
    now = datetime.datetime.now().astimezone().strftime("%Y-%m-%d %H:%M:%S %Z")
    cost, credits = TEST_PAIRS[0]
    out = []
    if complete:
        out.append("Status : COMPLETE - all checks passed")
    else:
        out.append("Status : INCOMPLETE - at least one check did not pass")
    out.append("Points : {} / {}  (from check.py; counts only when the Git and GitHub checks pass)".format(points_earned(), POINTS_POSSIBLE))
    out.append("")
    out.append("CS 1430 Assignment 2: The Cost of College")
    out.append("GitHub user : " + (gh_user or "unknown"))
    out.append("Repository  : " + (repo_url or "unknown"))
    out.append("Commit      : " + commit.get("sha", "unknown"))
    out.append("Message     : " + commit.get("message", ""))
    out.append("Author      : " + commit.get("author", ""))
    out.append("Committed   : " + commit.get("date", ""))
    out.append("Checked     : " + now)
    out.append("Python      : " + sys.version.split()[0])
    out.append("")
    out.append("=" * 64)
    out.append("CHECK RESULTS")
    out.append("=" * 64)
    out.append(report)
    out.append("=" * 64)
    out.append("PROGRAM OUTPUT  (typed: {}, {}, 1, 2, 3, 4, 5, Q)".format(cost, credits))
    out.append("=" * 64)
    out.append(transcript.rstrip())
    out.append("")
    with open(RECEIPT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(out))


if __name__ == "__main__":
    sys.exit(main())
